# -*- coding: utf-8 -*-
"""ML_Project_Rodrigo_Santos_eng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AfIz1z0e__KGVbB_dr3oVa8R6pNsdlh

# FINAL PROJECT — Volis Case Study

Name of the student: Rodrigo Santos

Dataset: volis_dataset.csv

Submission: this notebook (.ipynb) duly completed and reproducible

## 0) Imports and configurations
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.impute import SimpleImputer # Added SimpleImputer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster

# Metrics
from sklearn.metrics import silhouette_score, adjusted_rand_score

# For reproducible results
RANDOM_STATE = 42

"""## 1) Data loading"""

DATA_PATH = "volis_dataset.csv"
df = pd.read_csv(DATA_PATH)
df.head()

"""## 2) Dataset overview"""

print("Dimension (rows, columns):", df.shape)
display(df.sample(5, random_state = RANDOM_STATE))
n_lines = df.shape[0]
n_cols = df.shape[1]
print("\nData types:")
print(df.dtypes)

print("\nStatistical summary (numerical):")
display(df.describe())

# Organize the dataset into variable X (only numerical values) and y (numerical target)
X = df.copy()
X = X.drop(columns = ['nm_college'])
X = X.drop(columns = ['bl_private'])
y = pd.DataFrame(df["bl_private"], columns = ["bl_private"])
col_names = X.columns.tolist() # List with numerical variable names

print("\nBoxplot for all variables")
plt.figure(figsize = (25,25))
for i in range(len(col_names)): # Boxplot for all numerical variables
    plt.subplot(5,4,i+1)
    sns.boxplot(X[col_names[i]])
    plt.title(col_names[i])
plt.show()

"""In this first approach, we got an overview of the dataset.

*   We were able to understand how many rows (instances) and how many variables (numerical and categorical) there are.

*   The dataset was also organized into two variables **X** (numerical variables) and **y** (targets), which will be useful later in the program.

*   A statistical summary and boxplots were also generated for each numerical variable: it is observed that there are variables that present outliers, different range scales between variables, something that will have to be treated later in data preparation.

## 3) Data quality: missing values and duplicates
"""

#Nulls per column

null = df.isnull().sum() #Count of nulls per column
null_p = round(null/n_lines * 100,1) #Relative percentage of nulls

null_values = pd.DataFrame({"Number of nulls per column": null,
                            "Percentage (%)": null_p})
display(null_values) #Dataframe to visualize

#Duplicates
print("\nIs there any duplicated entry? ", df.duplicated().any())

#Imputation
imputer = SimpleImputer(strategy = 'median') #imputamos na variável X
X = pd.DataFrame(imputer.fit_transform(X), columns = col_names)

"""In this section, we were able to understand how many values were missing per variable and imputed them using the median, as the existing *outliers* are significant.

I decided to impute the _data_ instead of removing it from the original _dataset_, since our _dataset_ is not very large ("only" 977 instances). Removing all instances with null values would result in an even smaller _dataset_, which would compromise the reliability of the results.

## 4) EDA: distributions and outliers (minimum: 3 to 6 useful graphs)
"""

#In this section, we will deal with outliers and visualize the data
#after treatment

def outlier_summary(X): #We create a function to avoid repeating the code
                        #in the next section

  #We initialize three dictionaries that will store information on the number of outliers,
  #percentage and skewness for each column (dictionary keys)
  upper_counts = {} #upper outliers
  lower_counts = {} #lower outliers
  outlier_percentages = {} #percentage of outliers per variable
  skewness_values = {} #skewness value per variable

  #We use the "for" loop to evaluate each column:
  for col in col_names:
    #We calculate Q1, Q3 and IQR (interquartile range)
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1

    #We calculate the outlier limits for each quartile
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    #We identify the outliers and store them in the dictionaries
    upper_counts[col] = len(X[(X[col] > upper_bound)])
    lower_counts[col] = len(X[(X[col] < lower_bound)])
    outlier_percentages[col] = round((upper_counts[col]+lower_counts[col])/X.shape[0] * 100, 1)
    skewness_values[col] = round(X[col].skew(), 2)

  #We create a dataframe to better visualize the results of the "for" loop
  summary_X = pd.DataFrame({
      "Upper Outliers": pd.Series(upper_counts),
      "Lower Outliers": pd.Series(lower_counts),
      "Total Outliers:": pd.Series(upper_counts) + pd.Series(lower_counts),
      "Outlier Percentages (%)": pd.Series(outlier_percentages),
      "Skewness": pd.Series(skewness_values)
  })
  return summary_X

summary_X = outlier_summary(X)

#We visualize the dataframe in descending order of Skewness.
display(summary_X.sort_values(by = "Skewness", ascending = False))

"""In this code section, our goal is to create an evaluation criterion for *outliers* and understand the distribution of values within the variables. We observe that:

*   There are variables with a large number of *outliers*, representing up to 14.4% of the _data_ for that column
*   Most *outliers* occur above the upper limit
*   There are columns with a large right tail dictated by a skewness value much greater than 1

Considering these three observations, in the next code section we will treat these columns through a data transformation.

Thus, I chose to select columns that:

*   Have an *outlier* percentage above **5%** OR
*   Have a *skewness* value above **4**
"""

no_transformation = ["pc_alumni_donors", "qt_top_25_percent", "pc_graduation_rate",
                     "pc_faculty_with_phd", "pc_faculty_with_terminal_degree"]

pt = PowerTransformer(method = "yeo-johnson")

for col in col_names:
  if col not in no_transformation:
    X[col] = pt.fit_transform(X[[col]])

summary_X = outlier_summary(X)
display(summary_X.sort_values(by = "Skewness", ascending = False))

"""In this section, data transformation was performed using the Yeo-Johnson method, as it showed to reduce the overall percentage of outliers and produce *skewness* values within or close to the range [-1, 1].

Logarithmic transformation worked well for high *outliers*, but not for low *outliers*, producing left-skewed distributions.
"""

plt.figure(figsize = (12,12))

#Columns to show pre and post-transformation
example_plot = ["qt_undergraduate_students", "qt_postgraduate_students",
                "vl_student_faculty_ratio", "vl_expenditure_per_student"]

for i in range(len(example_plot)):
    # Plot of original data
    plt.subplot(len(example_plot), 2, 2*i + 1)
    sns.histplot(df[example_plot[i]], kde = True, color = "red")
    plt.title(f"{example_plot[i]} (Original)")

    # Plot of transformed data
    plt.subplot(len(example_plot), 2, 2*i + 2)
    sns.histplot(X[example_plot[i]], kde = True, color = "blue")
    plt.title(f"{example_plot[i]} (Transformed)")

plt.tight_layout()
plt.show()

"""Example of four variables before and after Yeo-Johnson transformation.

## 5) Directed question (mandatory):
"""

target_grad = "pc_graduation_rate"

#Correlation matrix for all variables in X
full_corr_matrix = X.corr()

#DataFrame for the correlation vector of target_grad in descending order
target_corr = pd.DataFrame(full_corr_matrix[target_grad]).sort_values(by = target_grad, ascending = False)

# Heatmap for the correlation vector
#The closer to zero, the heatmap takes a white (neutral) color
#The further from zero, it can take a reddish color (positive correlation)
#or bluish color (negative correlation)

plt.figure(figsize = (10, 1))
sns.heatmap(target_corr.T, annot = True, cmap = "vlag", fmt = ".2f", cbar = True, center = 0)
plt.title(f"Correlation with {target_grad}")
plt.ylabel("Correlation")
plt.show()

#Select the n features with the highest correlation to target_grad
n = 3
top_corr = np.abs(target_corr.drop("pc_graduation_rate")).head(n).index.tolist()
print("-" * 100)
print(f"The {n} top correlations correspond to {top_corr}")
print("-" * 100)

#Example of the three correlation cases
y_example = ["qt_top_25_percent", "qt_undergraduate_students", "vl_student_faculty_ratio"] #example columns
colors = ["red", "black", "blue"] #list of colors for the graphs
titles = ["positive correlation (0.45)", "no correlation (0.00)", "negative correlation (-0.28)"]
print("\nExample of three scatter plots:")
plt.figure(figsize=(15,4))
for i in range(len(y_example)):
    plt.subplot(1,3,i+1)
    plt.scatter(X["pc_graduation_rate"], X[y_example[i]], s = 4, c = colors[i])
    plt.xlabel(target_grad)
    plt.ylabel(y_example[i])
    plt.title(titles[i])

"""* The variables that seem most relevant are those with an absolute correlation coefficient greater than 0.40: *"qt_top_25_percent"*, *"pc_alumni_donors"* and *"qt_top_10_percent"*.

* The correlation of these 3 variables is expected, since the graduation rate correlates positively with a higher percentage of students who already had academic success in their previous school, and with a greater investment from alumni.

* However, there may be some spurious correlation in some variables. In the case of *"vl_tuition_outstate"* and *"vl_room_board"*, which appear in 4th and 6th places in the top correlations, respectively, it is not necessarily true that the higher the tuition fees of an institution or the cost of accommodation and food, the higher the graduation rate. Therefore, the data must be observed carefully.

## 6) Question created by the student (mandatory)

Does the percentage of alumni donors vary between public or private institutions?
"""

plt.figure(figsize = (4, 3))

#Logical vectors for institution types (public vs. private)
public_institutions = y["bl_private"] == False
private_institutions = y["bl_private"] == True

#Data selection for each institution type
alumni_public_data = X.loc[public_institutions, "pc_alumni_donors"]
alumni_private_data = X.loc[private_institutions, "pc_alumni_donors"]

#Histogram plot for both variables
plt.figure(figsize = (8, 5))
sns.histplot(alumni_public_data, kde = True, color = "blue", label = "Public")
sns.histplot(alumni_private_data, kde = True, color = "red", label = "Private")
plt.title("Distribution of alumni donor percentage (Public vs. Private)")
plt.xlabel("Alumni donor percentage")
plt.ylabel("Frequency")
plt.legend()
plt.show()

#Comparison of medians
median_public = alumni_public_data.median()
median_private = alumni_private_data.median()
print(f"\nMedian of 'pc_alumni_donors' for Public institutions: {median_public:.2f}")
print(f"Median of 'pc_alumni_donors' for Private institutions: {median_private:.2f}")

"""Private institutions appear to have a significantly higher percentage of alumni donors compared to public institutions, as evidenced by the medians and the histogram distribution. The median for private institutions is considerably higher, and the distribution for private institutions is more shifted towards higher values to the right.

## 7) Choose 1 Machine Learning challenge
"""

CHALLENGE = "C"  # "A" = Classification | "B" = Regression | "C" = Clustering

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

# ============================================================
# 7C) CLUSTERING — institution segmentation
# ============================================================

# Impute missing values with the median before scaling
imputer = SimpleImputer(strategy='median')
X_imputed = imputer.fit_transform(X)

# Convert X_imputed back to a DataFrame to retain column names for clarity, though not strictly needed by StandardScaler
X_imputed_df = pd.DataFrame(X_imputed, columns=X.columns, index=X.index)

# 1st step - dataset standardization
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed_df)

# 2nd step - PCA calculation for 95% variance preservation and visualization
pca = PCA(n_components = 0.95)
X_pca = pca.fit_transform(X_scaled)
plt.scatter(X_pca[:, 0], X_pca[:, 1], s = 4)
plt.title("PCA")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""In the next section, we will use the k-Means method for creating *clusters*. After visualizing the data with PCA, we noticed that the distributions are reasonably spherical, so k-Means can be a good method to start clustering."""

#3rd step - let's calculate the best number of clusters
#using the elbow method and the silhouette score
sse = []
silhouette_scores = []
k_range = range(1, 11)

#calculation of the sum of squared errors (sse) and the silhouette score
#for k-numbers of clusters
for k in k_range:
    kmeans = KMeans(n_clusters = k, n_init = 10, random_state = 42)
    kmeans.fit(X_scaled)
    sse.append(kmeans.inertia_)
    labels = kmeans.fit_predict(X_scaled)
    if k > 1: # Silhouette score requires k>1
        silhouette_scores.append(round(silhouette_score(X_scaled, labels),2))
    else:
        silhouette_scores.append(np.nan)

#DataFrame for better representation of silhouette scores
silhouette = pd.DataFrame({
    "Número de clusters": k_range,
    "Silhouette score": silhouette_scores})

#Plot of the elbow method
plt.figure()
plt.plot(k_range, sse, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of clusters (k)')
plt.ylabel('Inertia (SSE)')
plt.grid(True)
plt.show()
#Display of silhouette scores
display(silhouette)

"""* From k = 3, the decrease in error (SSE) is no longer very sharp.
* It is also confirmed that k = 3 has the highest silhouette score, demonstrating better data separation.
* Thus, we choose the value k = 3 for the number of *clusters*.
"""

kmeans_final = KMeans(n_clusters = 3, n_init = 10, random_state = 42)
y_kmeans = kmeans_final.fit_predict(X_scaled)

"""To visualize the *clusters* formed through a two-dimensional representation, we will use PCA in the next section for its representation."""

#Visualization of clusters
plt.scatter(X_pca[:, 0], X_pca[:, 1], s = 4, c = y_kmeans, cmap = "viridis")

#Assignment of each scatter plot color to a cluster in the legend
unique_clusters = np.unique(y_kmeans)
cmap = plt.get_cmap('viridis', len(unique_clusters))
legend_colors = [cmap(i) for i in unique_clusters]
handles = [
    mpatches.Patch(color=legend_colors[i], label=f'Cluster {unique_clusters[i]}')
    for i in range(len(unique_clusters))]

#Final Plot
plt.legend(handles = handles, loc = 'center left', bbox_to_anchor = (1, 0.5))
plt.title("PCA")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""We can observe the three reasonably defined *clusters*.
In the next section, we will evaluate the profile of each cluster through its centroid.
"""

#Creation of a DataFrame for the centroids of each cluster
centers = pd.DataFrame(
    kmeans_final.cluster_centers_,
    columns = X.columns)

#Calculation of the maximum value (important for the heatmap scale)
vmax = np.abs(centers.values).max()

#Creates a new dataframe of centers, where the columns are sorted
#in descending order of standard deviation. This separation helps to visualize
#differences between clusters in the heatmap.
centers_sorted = centers[centers.std().sort_values(ascending=False).index]

plt.figure(figsize=(14,6))
sns.heatmap(centers_sorted, cmap = "vlag", center=0, #Center (neutral color)
            vmin=-vmax, #Symmetric of the maximum value
            vmax=vmax, linewidths=0.5, annot=True, fmt=".2f")

plt.title("Cluster Profiles (Standardized & Sorted)")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""As expected, the 3 *clusters* have distinct profiles from each other.

*   **Cluster 0**: characterized by colleges that have a higher percentage of **top 10 and 25 students** from their original schools, **higher percentage of alumni donations, faculty with PhDs, faculty spending per student, and graduation rate, lower student/faculty ratio (allowing for better support)**. Students at these institutions also have **higher tuition, room, and board expenses**.

*   **Cluster 1**: characterized by a **high number of applications and enrolled students**. In contrast, the characteristics increased in cluster 0 **appear diminished here**. Possibly, this cluster will concentrate **public institutions**.

*   **Cluster 2**: characterized by a **general decrease in all characteristics**. Possibly, these will be **small institutions** (mostly private). It is the cluster with the most distinct profile of all, which is also confirmed through the PCA graphical representation.

It should also be noted that the book price variable remained constant across all three _clusters_, being therefore irrelevant for this clustering and could even be removed.

As expected, we observe **an increase in the graduation rate in institutions in the _cluster_ that receive more investment from _alumni_, invest more in their students, and where there is greater student support from faculty**. Thus, an important management action to maximize the graduation rate in other institutions would be to focus on investing in student support.

With the analysis of each *cluster*'s profile, the question arises: "how can the type of institution, public vs. private, influence its profile? Is there any trend within each *cluster*?"
"""

#What is the percentage of public and private institutions in each cluster?
cluster_data = y.copy()
cluster_data['cluster'] = kmeans_final.labels_ #adds the cluster_id to the initial dataframe

#Dictionary for each percentage value per cluster
public_percent = {}
private_percent = {}
no_value_percent = {}

#Stores the values in the dictionary
for i in range(3):
    cluster = cluster_data[cluster_data['cluster'] == i]
    public_percent[i] = round(cluster[cluster['bl_private'] == 0].shape[0]/cluster.shape[0]*100, 1)
    private_percent[i] = round(cluster[cluster['bl_private'] == 1].shape[0]/cluster.shape[0]*100, 1)
    no_value_percent[i] = round(int(cluster['bl_private'].isnull().sum())/cluster.shape[0]*100, 1)

# Creates a DataFrame from the created dictionaries
plot_df = pd.DataFrame({
    'Public': list(public_percent.values()),
    'Private': list(private_percent.values()),
    'No information': list(no_value_percent.values())})

#Visualization of percentages through a heatmap
plt.figure(figsize=(5, 3))
sns.heatmap(plot_df, annot=True, cmap='vlag')
plt.title('Distribution of Institution Types by Cluster')
plt.xlabel('Institution type')
plt.ylabel('Cluster')
plt.show()

"""From the combined analysis of the *heatmap* above and the profile of each *cluster*, the following conclusions are drawn:
*   As expected, **cluster 0** is essentially formed by **private institutions**, which justifies its **more exclusive profile** (fewer students, students with high grades, and higher expenses per student).

*   **Cluster 1** shows a majority of **public institutions**, which was expected, as it has a larger number of applications and students.

*   **Cluster 2** presents a case of **smaller institutions**, where most are private.

**Should I have chosen another clustering method?**

As observed, the k-Means algorithm with k=3 produces a reasonable silhouette score (0.21), but close to the threshold for not indicated (<0.20). In addition, it is also observed that some values within each cluster are far from their centroid, which also influences its computation.

Thus, it is legitimate to ask whether the k-Means method is the most appropriate; and if using, for example, a hierarchical method would not be more appropriate for the separation of subtypes.

Now trying a hierarchical method...
"""

#Hierarchical clustering using the "ward" method (compact clusters)
linked_data = linkage(X_scaled, method="ward")

#Plot of the dendrogram
plt.figure(figsize=(15, 8))
dendrogram(linked_data)
plt.title("Dendrogram for Hierarchical Clustering")
plt.xlabel("Instance Index")
plt.ylabel("Distance")
plt.show()

"""The analysis of the dendrogram shows us that this hierarchical clustering algorithm produced:
*   Three *clusters* at a reasonable distance;
*   The 2nd and 3rd *clusters* are hierarchically closer.
"""

#Comparing the number of instances of each cluster formed by k-Means and by
#hierarchical clustering
num_clusters_hierarchical = 3
hierarchical_labels = fcluster(linked_data, num_clusters_hierarchical, criterion = "maxclust")
crosstab_labels = pd.crosstab(pd.Series(y_kmeans, name = "KMeans Cluster"),
                              pd.Series(hierarchical_labels - 1, name = "Hierarchical Cluster"))
display(crosstab_labels)

#Adjusted Rand Index - evaluates the similarity between clustering algorithms
ARS = adjusted_rand_score(y_kmeans, hierarchical_labels - 1)
print(f"\nAdjusted Rand Score: {ARS:.2f}")

#Silhouette score again to compare the two methods
silhouette_kmeans = silhouette_score(X_scaled, y_kmeans)
silhouette_hierarchical = silhouette_score(X_scaled, hierarchical_labels - 1)

print(f"Silhouette Score (K-Means): {silhouette_kmeans:.2f}")
print(f"Silhouette Score (Hierarchical): {silhouette_hierarchical:.2f}")

"""If we compare the total number of instances assigned to the *clusters* formed by k-Means and by hierarchical clustering, we verify that:
*   Both algorithms produce three *clusters* consistently;

*   **K-Means cluster 0** shares the majority of its instances with hierarchical algorithm cluster 0 (cluster overlap);

*   **K-Means cluster 1** aligns the majority of its instances with hierarchical cluster 2;

*   **K-Means cluster 2** aligns a larger percentage of its instances with hierarchical cluster 1, however there is some _leakage_ into clusters 0 and 2.

Comparing the two algorithms by the _adjusted rand index_ we obtain a value of 0.29, meaning that the two algorithms produce distinct results, mainly due to the _leakage_ that occurred in **K-Means cluster 2**.

On the other hand, the silhouette score of k-Means is **superior** to that of the hierarchical method.

Thus, it was decided to keep k-Means as the analysis algorithm.

## 8) Conclusions and final reflection (mandatory)

1) During the EDA, we saw that the scales between variables had different ranges, there were missing values, and also a significant amount of *outliers* (upper and lower) per variable.
To deal with the existence of *outliers* (critical for k-Means), **we proceeded with data transformation using the Yeo-Johnson method**. It was found that the application of the **logarithmic function** dealt well with upper *outliers*, decreasing the right tail, however, **lower _outliers_ were not altered**.
The **Yeo-Johnson method** was the one that simultaneously managed to **better deal with lower and upper _outliers_**, creating a _dataset_ with smaller percentages of *outliers* and *skewness* values closer to the range [-1, 1].

2) After preparing the data, we correlated the different variables with the variable *"pc_graduation_rate"* which evaluates the academic success of educational institutions. We observed that the **3** variables that most positively influence the academic success rate are: the **percentage of top 25 and top 10 students from their original schools and the percentage of _alumni_ donors**.
This is expected, as there is a tendency for students with good past results to continue achieving good results. On the other hand, *alumni* donations will be used to invest in teaching conditions, **enabling good learning and a better graduation rate**. As already mentioned above, it is necessary to pay attention to data analysis due to the existence of spurious correlation in some variables.

3) The chosen ML challenge, using unsupervised learning, allowed us to answer **whether there are different profiles of colleges, regardless of their type (public vs. private)**. The best approach, considering the _elbow plot_ and the _silhouette score_, revealed that the existence of three *clusters* would be the most reliable for the k-Means algorithm. These three *clusters* allowed identifying three distinct profiles:
* Cluster 0: Institutions with higher investment and graduation rate, where the best students are concentrated. **(~95% private)**

* Cluster 1: Larger institutions with less investment and lower graduation rate. **(~75% public)**

* Cluster 2: Small institutions with little investment. **(~72% private)**

  If the chosen challenge had used supervised learning, we would have missed these sub-populations and diversity within each public or private subtype.

  It is also concluded that investment in education is key to better academic performance.

4) The provided _dataset_ allows us to confirm, through data analysis, something that seems intuitive to us:
**Academic success depends on the college's investment capacity per student.**
  
  The data presented for institutions that **receive more donations**, have a **lower student-to-faculty ratio**, and **higher spending/investment per student** show significantly **better graduation results**.

  However, there is some missing data here for a complete analysis of this investment, as we do not have access to data on the **total budget** of educational institutions.

  It is necessary to understand in the **total budget** what percentage corresponds to **tuition fees** of each institution, what is the percentage contribution of **_alumni_ donations**, if there are sources of **external funding** or **public-private partnerships**.

  It is also necessary to understand what the **target of expenses** will be for the budgets: hiring professors and non-teaching staff, maintaining research departments (certain departments will have more expenses than others), management activities, among others.

  Only then will we be able to have information on the **budgetary profile** of each institution and propose **better management methods** to **maximize the graduation rate** without jeopardizing the proper functioning of other sectors of the college.
"""